# Generated by Django 6.0.1 on 2026-01-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='department',
        ),
        migrations.AlterModelOptions(
            name='employeeuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='employeeuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='departament',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.company'),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
