# Generated by Django 6.0.1 on 2026-02-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
